# Jekyll Configuration
title: Volunteering and Social Action Ontology
base_url: https://standard.volunteeringdata.io
description: Standards for volunteering and social action
theme_color: "#0f4b69"
contact: volunteeringdata@theodi.org
github_username: volunteeringdata
repository: volunteeringdata/standard
homepage:
  title: Volunteering Data
  url: /
nav:
  - title: Data Model
    url: /ontology
  - title: Use Cases
    url: /use-cases
  - title: Working Group
    url: /working-group
pagefind: true
footer:
  copyright:
    title: Crown Copyright
    url: http://www.nationalarchives.gov.uk/information-management/re-using-public-sector-information/copyright-and-re-use/crown-copyright/
  license:
    title: Open Government License v3
    url: https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/
styles:
  input: /assets/css/
  output: /assets/css/styles.css
  rouge_theme: github
  minify: true
syntax_highlighting_scheme: github
excerpt_separator: "<!--more-->"
plugins:
  - jekyll-feed
include: 
  - _pages
exclude:
  - docker-compose.yml
  - LICENSE
  - README.md
markdown: kramdown
kramdown:
  parse_block_html: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
rouge_theme: github
