# Jekyll Configuration
title: Volunteering and Social Action Ontology
base_url: https://standard.volunteeringdata.io
description: Standards for volunteering and social action.
github_username: volunteeringdata
repository: volunteeringdata/standard
homepage:
  title: Volunteering Data
  url: /
nav:
  - title: Data Model
    url: /ontology/
  - title: Use Cases
    url: /use-cases/
  - title: Working Group
    url: /working-group/
footer:
  copyright:
    title: Crown Copyright
    url: http://www.nationalarchives.gov.uk/information-management/re-using-public-sector-information/copyright-and-re-use/crown-copyright/
  license:
    title: Open Government License v3
    url: https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/
excerpt_separator: "<!--more-->"
plugins:
  - jekyll-feed
include: 
  - _pages
  - assets/css/styles.css
exclude:
  - assets/css
  - docker-compose.yml
  - LICENSE
  - README.md
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
rouge_theme: github
