# Jekyll Configuration
title: Volunteering and Social Action Ontology
base_url: https://standard.volunteeringdata.io
description: Standards for volunteering and social action.
github_username: volunteeringdata
repository: volunteeringdata/standard
homepage:
  title: Volunteering Data
  url: /
nav:
  - title: Data Model
    url: /ontology/
  - title: Use Cases
    url: /use-cases/
  - title: Working Group
    url: /working-group/
plugins:
  - jekyll-feed
excerpt_separator: "<!--more-->"
include: 
  - _redirects
exclude:
  - scripts
  - docker-compose.yml
  - LICENSE
  - LICENSE.MIT
  - README.md
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
rouge_theme: github
